name: Deployment pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: npm install
        
      - name: Build the frontend
        run: npm run build:ui:ubuntu --if-present

        env:
          VITE_APP_BASE_URL: /api/products
          VITE_LOGIN_URL: /api/login
          VITE_REGISTER_URL: /api/users
          VITE_CART_URL: /api/cart
          VITE_CARTITEM_URL: /api/cartItem
          VITE_EMAIL_URL: /api/email
          VITE_ORDER_URL: /api/order
          VITE_ORDERITEM_URL: /api/orderItem

      - name: Start backend server
        run: npm run start-prod
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
           project: ./webstore
           start: npm run start-prod
           wait-on: http://localhost:3001
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
      
      - name: Zip artifact for deployment
        run: zip -r release.zip dist controllers models util app.js index.js package.json package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6FC6E36A06E5437BBA220646AA6AD2AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_961F7C40868A411FA2C870653752940E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A9D906C76E4D4A0985A292D995D74871 }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodonline'
          slot-name: 'Production'
          package: .
          