name: Deployment pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build:ui:ubuntu --if-present

      - name: e2e tests
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
        env:
          VITE_APP_BASE_URL: /api/products
          VITE_LOGIN_URL: /api/login
          VITE_REGISTER_URL: /api/users
          VITE_CART_URL: /api/cart
          VITE_CARTITEM_URL: /api/cartItem
          VITE_EMAIL_URL: /api/email
          VITE_ORDER_URL: /api/order
          VITE_ORDERITEM_URL: /api/orderItem

      - name: Zip artifact for deployment
        run: zip -r release.zip dist controllers models util app.js index.js package.json package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: deployment_pipeline
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6FC6E36A06E5437BBA220646AA6AD2AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_961F7C40868A411FA2C870653752940E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A9D906C76E4D4A0985A292D995D74871 }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodonline'
          slot-name: 'Production'
          package: .