name: Build and deploy Node.js app to Azure Web App - FoodOnlineApp

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build:ui:ubuntu --if-present
        env:
          VITE_APP_BASE_URL: /api/products
          VITE_LOGIN_URL: /api/login
          VITE_REGISTER_URL: /api/users
          VITE_CART_URL: /api/cart
          VITE_CARTITEM_URL: /api/cartItem
          VITE_EMAIL_URL: /api/email
          VITE_ORDER_URL: /api/order
          VITE_ORDERITEM_URL: /api/orderItem

    
      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start-prod
          wait-on: 'http://localhost:3001'
          command: npm run test:e2e
          config-file: cypress.config.js
          browser: chrome
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET: ${{ secrets.SECRET }} 


      - name: Remove Cypress and other dev dependencies
        run: |
          cd ./webstore
          npm prune --production

      - name: Zip artifact for deployment
        run: zip -r release.zip dist controllers models util app.js index.js package.json package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6802E4526DB5450CA72F4B246B56021F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC270E454CBE4E23A4679B276F3C4684 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A9C56123886D4F3F83AFCE2DA9870B7B }}
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodonline'
          slot-name: 'Production'
          package: .