name: Build and deploy Node.js app to Azure Web App - FoodOnlineApp

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          # npm run test --if-present
          npm run build:ui:ubuntu --if-present
          cd ./webstore
          # npm run test --if-present
        env:
          VITE_APP_BASE_URL: /api/products
          VITE_LOGIN_URL: /api/login
          VITE_REGISTER_URL: /api/users
          VITE_CART_URL: /api/cart
          VITE_CARTITEM_URL: /api/cartItem
          VITE_EMAIL_URL: /api/email
    
      - name: Remove Cypress and other dev dependencies
        run: |
          cd ./webstore
          npm prune --production

      - name: Zip artifact for deployment
        run: zip -r release.zip dist controllers models util app.js index.js package.json package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodonline'
          slot-name: 'Production'
          package: .